### ISSUE TITLE
한글패치가 제대로 작동하지 않습니다

### ISSUE THREAD

**Issue by deodeumii** [dvrp0/ProperKorean-Balatro#1]
https://dvrp-balatro-mods.pages.dev/properkorean

위 링크를 따라 동일하게 진행했는데, 한글패치가 제대로 이루어지지 않았습니다.

![112](https://github.com/dvrp0/ProperKorean-Balatro/assets/146622879/99d4e330-2595-467f-b0bd-31ae90977b83)

**Comment by dvrp0** [comment]
한국어로 언어를 변경해도 적용이 안 되었다는 말씀이시죠? 첨부하신 사진으로 보면 Lovely 패치는 제대로 진행된 것으로 보이는데 이상하네요. 혹시 다운받으신 Lovely 버전이 `v0.5.0-beta1`인가요?

`v0.4.0`이시라면 `%AppData%\Roaming\Balatro\Mods\lovely\dump\@game.lua` 파일의 `Game:set_language()` 함수에서 끝 부분이

```lua
local localization = love.filesystem.getInfo('localization/'..G.SETTINGS.language..'.lua')
if localization ~= nil then
    self.localization = assert(loadstring(love.filesystem.read('localization/'..G.SETTINGS.language..'.lua')))()
    apply_properkorean()
    init_localization()
end
```
이렇게 되어 있는지 한번 확인 부탁드립니다

**Comment by deodeumii** [comment]
local localization = love.filesystem.getInfo('localization/'..G.SETTINGS.language..'.lua')
    if localization ~= nil then
      self.localization = assert(loadstring(love.filesystem.read('localization/'..G.SETTINGS.language..'.lua')))()
      apply_properkorean()
      init_localization()
    end

이렇게 되어 있고, lovely 버전은 0.4.0입니다

**Comment by dvrp0** [comment]
코드로만 보면 안 될 이유가 없는데 상당히 이상하네요 😕 옵션에 있는 크레딧도 영문으로 나오나요?

**Comment by deodeumii** [comment]
크레딧 한글로 나옵니다! 한글 패치가 된거같기도 하고 아닌거같기도 하고 아리송하네요,, 여전히 게임 실행시 같이 실행되는 검은색 콘솔에는 아래 사진처럼 나옵니다
![111](https://github.com/dvrp0/ProperKorean-Balatro/assets/146622879/c511255b-ebd0-493a-971a-cd1148ea2f58)

**Comment by deodeumii** [comment]
크레딧은 한글로 잘 나오는데, 검은색 콘솔 화면은 여전히 아래처럼 나옵니다
![33](https://github.com/dvrp0/ProperKorean-Balatro/assets/146622879/9a63e104-df40-4439-82e3-16dfb7b16102)

**Comment by dvrp0** [comment]
![스크린샷 2024-04-25 153519](https://github.com/dvrp0/ProperKorean-Balatro/assets/26036938/5ed16c60-76e2-4f22-913e-d0653dde1e43)

컬렉션에서 이 조커 이름이 음욕으로 되어 있으면 적용된 건데 한번 확인해 보세요
콘솔에서 패치 0건 적용됨 이렇게 나오는 건 Lovely 자체 출력 버그라 패치랑은 상관 없습니다

**Comment by deodeumii** [comment]
확인해보니 제대로 적용돼있습니다
콘솔 화면에서 안돼있어서 적용 안된줄 알았네용 ㅜ 답변해주셔서 감사합니다!

**Comment by dvrp0** [comment]
다행이네요 👍
